<?php
/**
 * Company: Atölye15
 * URI: http://www.atolye15.com
 * Author: Muhittin Özer <muhittin@atolye15.com>
 */

namespace Atolye15;

/**
 * The Verify class exposes two services for sending users a verification token (a three to five-digit number).
 * You can use this mechanism to simply test whether you can reach users at the phone number they supplied,
 * or you can have them use the token to authenticate themselves with your web application. In addition, this class
 * also exposes a service that allows you to confirm the result of the authentication.
 *
 * @package  Telesign
 * @access   public
 */
class Verify extends Telesign
{
	/**
	 * Make a Verify API call to TeleSigns phone service. Calling this method
	 * results in an automated phone call made to the given identifier. The language
	 * is specified as a string. Extensions and delays are programmable using the
	 * extension_type and extension template.
	 *
	 * @link https://portal.telesign.com/docs/content/verify-call.html
	 *
	 * @param string $phone_number The phone number of the person to dial
	 * @param string $verify_code [optional] if null, verify code will be generated by telesign
	 * @param string $language [optional] The language code of the call
	 * @param string $verify_method [optional] Only available option is currently null (dictated code) or "keypress"
	 * @param string $extension_type [optional] If 0, no extension. if 1, DTMF extension. If 2, voice extension
	 * @param string $extension_template [optional] If null not used. Otherwise the extension to reach
	 * @param string $redial [optional]
	 * @param array  $more [optional]
	 *
	 * @return string The fully formed response object repersentation of the JSON reply
	 */
	public function call(
		$phone_number,
		$verify_code        = "",
		$language           = "",
		$verify_method      = "",
		$extension_type     = "",
		$extension_template = "",
		$redial             = "",
		$more               = []
	)
	{
		if (!empty($language)) {
			$more['language']           = $language;
		}
		if (!empty($verify_method)) {
			$more['verify_method']      = $verify_method;
		}
		if (!empty($extension_type)) {
			$more['extension_type']     = $extension_type;
		}
		if (!empty($extension_template)) {
			$more['extension_template'] = $extension_template;
		}
		if (!empty($redial)) {
			$more['redial']             = $redial;
		}
		return $this->verify($phone_number, $verify_code, 'call', $more);
	}

	/**
	 * Make a Verify SMS request to TeleSign's API. This method allows
	 * the language, verification code and template of the message to be set.
	 *
	 * @link https://portal.telesign.com/docs/content/verify-sms.html
	 *
	 * @param string $phone_number The phone number to send the sms message
	 * @param string $verify_code [optional] The code to send via sms. Set to null to let Telesign generate the code
	 * @param string $language [optional] The String representation of the language to send the sms message
	 * @param string $template [optional] The template of the message that is being sent. Set to null for default, otherwise must include $$CODE$$ as a variable placeholder
	 *
	 * @return string The fully formed response object repersentation of the JSON reply
	 */
	public function sms($phone_number, $verify_code = "", $language = "", $template = "")
	{
		$more = [];
		if (!empty($language)) {
			$more['language'] = $language;
		}
		if (!empty($template)) {
			$more['template'] = $template;
		}
		return $this->verify($phone_number, $verify_code, 'sms', $more);
	}

	/**
	 * Return the results of the post referenced by the reference_id. After a verify
	 * SMS or Call has been made, the status of that verification request can be retrieved
	 * with this method.
	 *
	 * @param string $reference The id returned from either requestsSMS or requestCall
	 * @param string $verify_code [optional] The verification code received from the user
	 *
	 * @return string The fully formed response object repersentation of the JSON reply
	 */
	public function status($reference, $verify_code = "")
	{
		// build verify url
		$resource       = "/v1/verify/" . $reference;
		$url            =
			$this->api_url .
			$resource .
			(strlen($verify_code) ? ("?verify_code=" . $verify_code) : "")
		;

		curl_setopt($this->curl, CURLOPT_URL, $url);
		$this->method       = "GET";
		$this->content_type = "text/plain";
		$this->_sign($resource);

		return json_decode($this->_submit_and_get_response(), TRUE);
	}
}